### ISSUE TITLE
Building for x86_64x Produces Error

### ISSUE THREAD

**Issue by thecoolwinter** [supabase-community/postgrest-swift#17]
When building for the simulator and excluding arm64 architecture I get this error:
```
Could not find module 'PostgREST' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator
```

I need to exclude arm64 to build other static libraries, but am hitting this error and can't build for the simulator.

PostgREST version: Master branch
iOS: 15.0
Xcode: Version 13.0 (13A233)

Build settings:
<img width="452" alt="Screen Shot 2021-10-20 at 10 01 31 AM" src="https://user-images.githubusercontent.com/35942988/138119042-6dc2ed96-ed02-42ff-b0bf-d2310170d139.png">

Error:
<img width="871" alt="Screen Shot 2021-10-20 at 10 02 25 AM" src="https://user-images.githubusercontent.com/35942988/138119155-d353d0c7-8d2f-4f4f-83df-f463dad2b298.png">

**Comment by grdsdev** [comment]
Is this still an issue @thecoolwinter ?
