### ISSUE TITLE
Provide parameter „returning:minimal“ for Swift

### ISSUE THREAD

**Issue by LeoHeuser** [supabase-community/postgrest-swift#18]
Currently you can't _only write_ (INSERT) a db with RLS on using Swift.

Because INSERT also return a SELECT. Therefore a db for e.g. feedback can also read by everyone with the _anon_ key. With a INSERT request you should be able to return a `returning:“minimal“` too.

So you can write to a db where RLS with only INSERT = true is on.

**Comment by thecoolwinter** [comment]
I've got a PR that adds this functionality! -> #19 Thanks for the suggestion.

**Comment by thecoolwinter** [comment]
PR #19 was merged so closing this now!

**Comment by LeoHeuser** [comment]
Thx for the feedback and very quick support!

I will test this later today.
FYI: I tried it with the PostgrestClient with this code:
`var database = PostgrestClient(url: "\(supabaseUrl)/rest/v1", headers: ["apikey":supabaseKey, "prefer":"return=minimal", "authorization":"Beare \(supabaseKey)"], schema: "public")`

And it "worked a bit". If I limit the database for "only write" I am unable to read - nice. If I send 10x a INSERT into the database I get 4/10 a RLS violation error; but the other 6 times a "success". Maybe this is also interesting for you.
So it works but not reliable.

**Comment by LeoHeuser** [comment]
And I tested your implementation: 10/10 INSERTS were successfully in a "only write" data base.
Seems like it works! Thx.

**Comment by thecoolwinter** [comment]
Awesome! Glad it's working!
