### ISSUE TITLE
example  for update pls

### ISSUE THREAD

**Issue by y0zong** [supabase-community/postgrest-swift#22]
I'm read supabase doc for dart and code swiftui like this, but I get error, pls send me a example for update action

``` swift
let val: Dictionary<String, Any> = ["username":"some username"]
let response = try supabaseClient.database.from("users").update(values: val).match(query: ["id": self.auth!.id.description]).execute()
```
`typeMismatch(Swift.Dictionary<Swift.String, Any>, Swift.DecodingError.Context(codingPath: [], debugDescription: "Expected to decode Dictionary<String, Any> but found an array instead.", underlyingError: nil))`

**Comment by grdsdev** [comment]
Hey @y0zong 

You can take a look into the integration tests for example usage for now.

https://github.com/supabase-community/postgrest-swift/blob/master/Tests/PostgRESTIntegrationTests/IntegrationTests.swift#L65-L69

If you still face issues after that, please let me know and I'd be glad on helping you.
