### ISSUE TITLE
Examples of more complex queries

### ISSUE THREAD

**Issue by matthewmorek** [supabase-community/postgrest-swift#36]
# Improve documentation

## Describe the problem

Currently, examples cover rudimentary applications, based on a simple Todo app concept, however it would be great to see how more complex queries can be fired, for example OUTER and INNER JOIN queries.

## Describe the improvement

How do you create queries to accommodate nested structs (SQL relationships) in Swift?

https://gist.github.com/matthewmorek/d88cf8c1c93503588016f5ff0875d29b

Sample SQL to achieve using query builder:
```sql
SELECT json_agg(
  json_build_object(
    'id', l.id,
    'url', l.url,
    'title', l.title,
    'category', json_build_object(
      'id', c.id,
      'name', c.name
    )
  )
) as links
FROM links l
JOIN categories c ON l.category_id = c.id
```

JSON output:
```json
[
  {
    "id": "15979e27-c446-4395-aed6-7b1651777aba",
    "url": "https://some.url/with/a/few/bits/",
    "title": "link title",
    "category": {
      "id": "955ed84a-9c58-4a57-9e6a-75ece7c50cbd",
      "name": "Category #1"
    }
  }
]
```

**Comment by grdsdev** [comment]
Hi @matthewmorek.

Unfortunately, I don't have the resources to add specific examples for the Swift libraries, but examples from the official JS library should work, just performing the required JS -> Swift translation.

If you find any example that doesn't work with this library, it can possible be a bug on `postgrest-swift`.

---

For your specific case, you can check the PostgREST documentation (https://postgrest.org/en/stable/api.html#resource-embedding).

Try something like this, embedding the `category` relationship on the `select(columns:)` method.
```swift
let response = try await client.database.from("links").select(columns: "*,category(*)").execute()
```

**Comment by matthewmorek** [comment]
Thanks for the tips. I might actually create a PR with a few more examples and a link to PostgREST docs, as I didn't know this was even a thing.

**Comment by grdsdev** [comment]
Sure, will close this then.
