### ISSUE TITLE
ilike query not finding strings when it contains a +

### ISSUE THREAD

**Issue by nyeu** [supabase-community/postgrest-swift#46]
# Bug report

## Describe the bug

I have a query that searches if a string is into a column called `email`. It works really well unless you search for emails that contain a +.

For example: 
- nyeu@mail.com would work perfectly
- nyeu+1@mail.com would not work

Both are valid emails and it should return the object.

Here's how I look for it:
`queryBuilder.ilike(column: "email", value: "%name+something@mail.com%")`

## To Reproduce

Search in a column for a string that contains a +.

## Expected behavior

It should work with and without the +. 

## System information

- OS: macOS Ventura 13.3
- Version of supabase-ios: 0.2.1

**Comment by tfoldi** [comment]
also does not work with `eq` operator. 

I have a fairly simple select:

```
try await supabase.database
            .from("table")
            .select() // keep it empty for all, else specify returned data
            .eq(column: "id", value: "Cigányka-ér (0+400 cskm) vízrajzi állomás")
            .execute()
            .value
```

and it does not find anything. Other values without `+` works fine.

**Comment by grdsdev** [comment]
Hey guys thanks for providing these examples, I think I was able to fix it on #48, can you guys give it a spin?

**Comment by tfoldi** [comment]
Tried to add that branch to my project, but have this error:

<img width="1295" alt="image" src="https://github.com/supabase-community/postgrest-swift/assets/82426/cf894efa-95d3-4039-b52b-084f93dc0cb0">

**Comment by grdsdev** [comment]
Fixed on https://github.com/supabase-community/postgrest-swift/releases/tag/1.0.2
