### ISSUE TITLE
Xcode 14.1 error when building

### ISSUE THREAD

**Issue by ahhhv** [supabase-community/postgrest-swift#51]
# Bug report

## Describe the bug

When I compile in Xcode, it produces an error that says: "Failed to produce diagnostic for expression; please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the project"

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Add package in xcode with SPM looking for "postgrest-swift"
2. Try to build

## Expected behavior

It builds successfully.

## Screenshots

<img width="1108" alt="imagen" src="https://github.com/supabase-community/postgrest-swift/assets/121790434/f5ea42c9-c27f-4c43-8d4a-6db0189259c7">

## System information

- OS: MacOS Ventura 13.5
- Xcode: 14.1

**Comment by tx-smitht** [comment]
I'm having the same issue

**Comment by samuelOsborne** [comment]
Same :-/
